#include <iostream>
#include "barycentric_random_points.hpp"
#include<algorithm>

int main(){
    ios_base::sync_with_stdio(false);
	RandomPoint<float> random_point_obj(4); 
    
    // A convex polygon 
    random_point_obj.AddPolygonCoordinate(make_pair(0,0));
    random_point_obj.AddPolygonCoordinate(make_pair(0,1));
    random_point_obj.AddPolygonCoordinate(make_pair(1,1));
    random_point_obj.AddPolygonCoordinate(make_pair(1,0));

    // calling function to generate random points 
    random_point_obj.GenerateRandomPoint(5);

    // Printing the random points generated by 
    random_point_obj.print();
}