#include <iostream>
#include "../includes/barycentric_random_pointsv2.hpp"
#include<algorithm>
#include<vector>
#include <boost/geometry.hpp>
#include <boost/geometry/geometries/point_xy.hpp>
#include <boost/geometry/geometries/polygon.hpp>

using namespace boost::geometry;
using namespace std;

int main()
{
    ios_base::sync_with_stdio(false);
    typedef model::d2::point_xy<double> point_xy;
    

    RandomPoint<double> random_point_obj(4); 

    // A convex polygon 
    random_point_obj.AddPolygonCoordinate(point_xy(0,0));
    random_point_obj.AddPolygonCoordinate(point_xy(0,5));
    random_point_obj.AddPolygonCoordinate(point_xy(5,5));
    random_point_obj.AddPolygonCoordinate(point_xy(5,0));

    // calling function to generate random points 
    random_point_obj.GenerateRandomPoint(5);

    // Printing the random points generated by 
    random_point_obj.print();
}
